# combination of environments from pytorch and tensorflow projects from vislab
# 28 april 2022
name: null

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython=1.83
  - ipykernel
  - ipython
  - matplotlib
  - numpy=1.26
  - pandas=2.2
  - pip=24.2
  - python=3.9
  - setuptools=75.1
  - scipy=1.12
