datasets:
  saudi: data/var-all-in-gnomad_mod.vcf

foldx_executable_name: foldx_20251231

chr_format: string
results_dir: annotation_output
data_dir: data
log_dir: annotation_logs
scripts_dir: workflow/scripts
max_variants_per_vep_run: 10000
max_jobs: 1900
uniprot_idmapping: resources/uniprot_2024_02/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz
alphafold_dir: resources/alphafold_human_v4
mane_dir: resources/alphafold_mane
dssp_alphafold: resources/alphafold_human_v4_dssp
dssp_mane: resources/alphafold_mane_dssp
panther: resources/panther/PTHR17.0_human_clean_2.pkl
pdbmodels: resources/pdbmodels.pkl
dssps: resources/dssps.pkl
